In [40]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

In [41]:
#create And Gate array
x=np.array([[0,0],[0,1],[1,0],[1,1]],"uint8")
y=np.array([[0],[0],[0],[1]],"uint8")

In [42]:
model = Sequential()  #Name of Network Name-model
model.add(Dense(units=1,activation='sigmoid',input_dim=2)) #Dense is a function 
model.compile(optimizer='adam',loss='binary_crosentropy',metrics=['accuracy'])

In [43]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x, y, epochs=50)

In [46]:
print(model.layers[0].get_weights())

[array([[-0.5287012],
       [-0.5834459]], dtype=float32), array([0.], dtype=float32)]


In [50]:
model.predict(x)

array([[0.5       ],
       [0.35814008],
       [0.37081987],
       [0.24747083]], dtype=float32)

In [51]:
#xor gate
x=[[0,0],[0,1],[1,0],[1,1]]
y=[[0],[1],[1],[0]]

In [53]:
xor = Sequential()  #Name of Network Name-model
xor.add(Dense(2,activation='sigmoid',input_dim=2)) #Dense is a function 
xor.add(Dense(1,activation='sigmoid'))
xor.compile(optimizer='adam',loss='binary_crosentropy',metrics=['accuracy'])
xor.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [54]:
xor.fit(x, y, epochs=5000)

Epoch 1/5000


ValueError: ignored

In [55]:
xor.get_weights()

[array([[-0.81154025, -0.6981898 ],
        [ 1.0736722 ,  0.12288463]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.8410989],
        [0.9476806]], dtype=float32),
 array([0.], dtype=float32)]

In [56]:
xor.predict(x)

array([[0.70979524],
       [0.75579906],
       [0.63957566],
       [0.69350004]], dtype=float32)

In [57]:
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

In [58]:
print(Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [60]:
features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [61]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(features,target,test_size=0.2)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)


In [63]:
from keras.models import Sequential
from keras.layers import Dense

In [66]:
model=Sequential()
model.add(Dense(32,input_dim=30,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [67]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accurasy'])

In [ ]:
model.summary()

In [ ]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

In [ ]:
score=model.evaluate(x_test,y_test)
print(score)

In [ ]:
predictions=model.predict(x_train)
label=[]
for pred in predictions:
  if pred >=0.5:
    print("Malignent")
  else:
    print("Benign")